# ==========================================================
# ROC PASSWORD MANAGER
# ==========================================================
Name: "RPM"
Version: 0.2.0
# ==========================================================
# SETTINGS
# ==========================================================
ClipboardClear: True
ClipboardTimer: 15